import NatsClient from './nats-client';

export type {
  NatsInjection,
  NatsValidationInjection,
  NatsAuthorizationInjection,
  NatsHandleInjection,
  NatsMiddlewareBeforeAllInjection,
  NatsMiddlewareAfterAllInjection,
  NatsMiddlewareValidationInjection,
  NatsMiddlewareAuthorizationInjection,
  NatsMiddlewareBeforeHandleInjection,
  NatsMiddlewareAfterHandleInjection,
  NatsValidationResult,
  NatsAuthorizationResult,
  NatsHandleResult,
  NatsMiddlewareBeforeAllResult,
  NatsMiddlewareAfterAllResult,
  NatsMiddlewareValidationResult,
  NatsMiddlewareAuthorizationResult,
  NatsMiddlewareBeforeHandleResult,
  NatsMiddlewareAfterHandleResult,
  NatsBeforeAll,
  NatsAfterAll,
  NatsBeforeValidate,
  NatsValidate,
  NatsAfterValidate,
  NatsBeforeAuthorize,
  NatsAuthorize,
  NatsAfterAuthorize,
  NatsBeforeHandle,
  NatsHandle,
  NatsAfterHandle,
  NatsMiddleware,
  NatsHandler,
} from './type';

export default NatsClient;
